# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

base:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-31 00:00
  time_step: 1h
  learning_mode: True
  exchange_units: null
  save_frequency_hours: 720

  learning_config:
    continue_learning: false
    trained_policies_save_path: null
    min_bid_price: -100
    max_bid_price: 100
    algorithm: matd3
    learning_rate: 0.0001
    # learning_rate_schedule: linear
    training_episodes: 10
    episodes_collecting_initial_experience: 5
    train_freq: 10h
    gradient_steps: 1
    batch_size: 128
    gamma: 0.99
    device: cpu #cuda:0
    # action_noise_schedule: linear
    noise_sigma: 0.1
    noise_scale: 1
    noise_dt: 1
    validation_episodes_interval: 5
    # early_stopping_steps: 10
    # early_stopping_threshold: 0.05

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

base_with_exchanges:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-31 00:00
  time_step: 1h
  exchange_units: exchange_units.csv
  save_frequency_hours: 720

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

tiny:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-02 00:00
  time_step: 1h
  save_frequency_hours: 24

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 1
          first_delivery: 1h
      opening_frequency: 1h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

dam:
  start_date: 2019-01-01 00:00
  end_date: 2019-01-31 00:00
  time_step: 1h
  exchange_units: null
  save_frequency_hours: 720

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 1h
      opening_frequency: 24h
      opening_duration: 1h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: pay_as_clear

dam_with_complex_clearing:
  start_date: 2019-01-01 00:00
  end_date: 2019-04-01 00:00
  time_step: 1h
  exchange_units: null
  save_frequency_hours: 720

  markets_config:
    EOM:
      operator: EOM_operator
      product_type: energy
      products:
        - duration: 1h
          count: 24
          first_delivery: 1h
      opening_frequency: 24h
      opening_duration: 24h
      volume_unit: MWh
      maximum_bid_volume: 100000
      maximum_bid_price: 3000
      minimum_bid_price: -500
      price_unit: EUR/MWh
      market_mechanism: complex_clearing
      param_dict:
        solver: highs
        pricing_mechanism: pay_as_clear
      additional_fields:
        - bid_type
        - min_acceptance_ratio
